version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile-FE  # Renamed for clarity
    ports:
      - "4000:80"
    environment:
      - BACKEND_URL=http://backend:5000

  backend:
    build:
      context: .
      dockerfile: Dockerfile-BE  # Renamed for clarity
    ports:
      - "5000:3000"